#!/usr/bin/perl
use strict;
use Data::Dumper;
use List::Util qw(shuffle);
use String::Utils qw(longest);
use Getopt::Long;

my $DEBUG = 0;

require("./screenfo.conf");
if($@) {
  warn($@);
}


# imported from configuration file
our($now_playing, $default_colorscheme, %colorschemes, $default_logo);


GetOptions(
  'logo:s'  => \$default_logo,
  'color:s' => \$default_colorscheme,
  help      =>  \&usage,
);
$default_logo = "./ascii/$default_logo"; # FIXME


sub get_kernel {
  open(my $fh, '<', '/proc/version') or warn($!);
  my $version = <$fh>;
  my ($kernel) = $version =~ /(2\.[0-9]\.[0-9]+)/;
  return($kernel);
}

sub get_gtk_info {
  my $wanted = shift // 'theme';
  my ($gtk_theme, $gtk_font, $gtk_icons, $gtk_toolbar_style) = undef;
  if(-f "$ENV{HOME}/.gtkrc-2.0") {
    open(my $fh, '<', "$ENV{HOME}/.gtkrc-2.0") or warn($!);
    while(<$fh>) {
      if(/gtk-theme-name="(.+)"/) {
        $gtk_theme = $1;
        print "GTK Theme: $gtk_theme\n" if($DEBUG);
      }
      if(/gtk-icon-theme-name="(.+)"/) {
        $gtk_icons = $1;
        print "GTK Icons: $gtk_icons\n" if($DEBUG);
      }
      if(/gtk-font-name="(.+)"/) {
        $gtk_font = $1;
        print "GTK Font: $gtk_font\n" if($DEBUG);
      }
      if(/gtk-toolbar-style=([0-9]+)/) {
        $gtk_toolbar_style = $1;
        print "GTK Toolbar Style: $gtk_toolbar_style\n" if($DEBUG);
      }
    }
  }
  return($gtk_theme)         if($wanted eq 'theme');
  return($gtk_icons)         if($wanted eq 'icons');
  return($gtk_font)          if($wanted eq 'font');
  return($gtk_toolbar_style) if($wanted eq 'toolbar');
  return(-1);
}

sub print_out {
  my $color = $default_colorscheme;
  my $logo = $default_logo;

  open(my $fh, '<', $logo) or die($!);
  my @logo = <$fh>;
  close($fh);

  if(exists($colorschemes{$color})) {
    $color = $colorschemes{$color};
  }
  else {
    $color = $colorschemes{ansi};
  }

  @$color = shuffle(@$color);

  #FIXME
  my $f = join('', @logo);
  @logo = split(/\n/, $f);
  #FIXME

  return(\@logo);
}

my $output = print_out($default_colorscheme, $default_logo);

my $long = longest(@$output);

@$output[0] = sprintf(
  "%-${long}s %12s: %s", @$output[0], 'OS', ucfirst(get_os())
);
@$output[1] = sprintf(
  "%-${long}s %12s: %s", @$output[1], 'WM', ucfirst(get_wm())
);
@$output[2] = sprintf(
  "%-${long}s %12s: %s", @$output[2], 'Kernel', get_kernel()
);
@$output[3] = sprintf(
  "%-${long}s %12s: %s", @$output[3], 'Theme', ucfirst(get_gtk_info())
);
@$output[4] = sprintf(
  "%-${long}s %12s: %s", @$output[4], 'Icons', ucfirst(get_gtk_info('icons'))
);
@$output[5] = sprintf(
  "%-${long}s %12s: %s", @$output[5], 'Font', ucfirst(get_gtk_info('font'))
);
@$output[6] = sprintf(
  "%-${long}s %12s: %s", @$output[6], 'Toolbar', get_gtk_info('toolbar')
);


for(@$output) {
  # Ugliest hack ever... FIXME
  if(/(.+)\s+([A-Za-z]+: .+)/) {
    print colorme($1), $2, "\n";
  }
  else {
    print colorme($_),"\n";
  }
}

sub colorme {
  my @foo = @_;
  my $f = join('', @foo);
  my @data = split(//, $f);
  my @toreturn;

  my $colorizer = undef;
  if(exists($colorschemes{$default_colorscheme})) {
    $colorizer = $colorschemes{$default_colorscheme};
  }
  else {
    $colorizer = $colorschemes{ansi};
  }

  @$colorizer = shuffle(@$colorizer);

  my $i = 0;
  for(@data) {
    if($i == scalar(@$colorizer)-1) {
      $i = 0;
    }
    if($_ eq '') {
      push(@toreturn, $_);
    }
    else {
      push(@toreturn, "\e[38;5;@$colorizer[$i]" . 'm' . $_ . "\e[0m");
    }
    $i++;
  }
  return(@toreturn);
}

sub get_wm { return('ratpoison'); }

sub get_os { return($^O); }

sub usage {
  print "--logo logo\n--color color\n" and exit(0);
}

# vim: set tw=0 nowrap:
